# Generated by Django 4.1.3 on 2023-03-11 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_exctended_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheckExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кол-во скачиваний')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Контроль загрузки Excel',
                'verbose_name_plural': '3. Контроль загрузок Excel',
            },
        ),
    ]
