# Generated by Django 4.1.3 on 2022-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название прайса')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, default='https://avaxdjango.herokuapp.com/minsk/export/', max_length=255, null=True, verbose_name='Ссылка')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колличество скачиваний')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': '4. Прайсы',
            },
        ),
        migrations.CreateModel(
            name='Nouskat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('note', models.CharField(max_length=255, verbose_name='Примечание')),
                ('active', models.BooleanField(default=True, help_text='Если установлен флажок, обьявление видно в боте', verbose_name='Активный')),
                ('sold', models.BooleanField(default=False, help_text='Если установлен флажок, обьявление продано', verbose_name='Продано')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Цена продажи')),
            ],
            options={
                'verbose_name': 'Ноускат',
                'verbose_name_plural': '3. Ноускаты',
            },
        ),
        migrations.CreateModel(
            name='PhotoNouskat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='public/image/')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentMinsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(max_length=50, verbose_name='Запчасть')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Колличество')),
                ('article', models.CharField(blank=True, max_length=100, null=True, verbose_name='Разборочный')),
                ('tk', models.CharField(max_length=50, verbose_name='Транспортная')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('type_send', models.CharField(max_length=100, verbose_name='Тип отправки')),
                ('information', models.CharField(blank=True, max_length=255, null=True, verbose_name='Информация')),
                ('username', models.CharField(max_length=20, verbose_name='Кто записал')),
                ('track', models.CharField(blank=True, max_length=50, null=True, verbose_name='Трек номер')),
                ('shipped', models.BooleanField(default=False, help_text='Если установлен флажок, значит уехало', verbose_name='Отгружено')),
                ('date_add', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отправка Минск',
                'verbose_name_plural': '2. Отправки Минск',
            },
        ),
        migrations.CreateModel(
            name='WarehouseMinsk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(verbose_name='Артикул')),
                ('mark_auto', models.CharField(max_length=100, verbose_name='Марка')),
                ('model_auto', models.CharField(max_length=250, verbose_name='Модель')),
                ('submodel_auto', models.CharField(max_length=250, verbose_name='Подмодель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('spare', models.CharField(max_length=100, verbose_name='Запчасть')),
                ('fuel', models.CharField(max_length=50, verbose_name='Топливо')),
                ('volume', models.FloatField(blank=True, null=True, verbose_name='Объем')),
                ('type_engine', models.CharField(max_length=50, verbose_name='Тип двигателя')),
                ('transmission', models.CharField(max_length=100, verbose_name='КПП')),
                ('original_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Маркировка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
                ('id_photo', models.CharField(blank=True, max_length=10, verbose_name='id фото')),
                ('photo', models.TextField(blank=True, null=True, verbose_name='Фото')),
                ('input_article', models.CharField(max_length=50, verbose_name='Разборочный')),
                ('vin', models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN')),
                ('id_video', models.CharField(blank=True, max_length=10, verbose_name='id видео')),
                ('video', models.CharField(blank=True, max_length=255, null=True, verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Наличие Минск',
                'verbose_name_plural': '1. Наличие Минск',
            },
        ),
    ]
