# Generated by Django 4.1.3 on 2023-01-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsk', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentminsk',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
    ]
