# Generated by Django 4.1.3 on 2023-03-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minsk', '0004_alter_warehouseminsk_input_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photonouskat',
            name='nouskat_id',
        ),
        migrations.DeleteModel(
            name='Nouskat',
        ),
        migrations.DeleteModel(
            name='PhotoNouskat',
        ),
    ]
