# Generated by Django 4.1.3 on 2023-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsk', '0005_remove_photonouskat_nouskat_id_delete_nouskat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPriceAvito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, default='https://avaxdjango.herokuapp.com/minsk/export/avito/', max_length=255, null=True, verbose_name='Ссылка')),
                ('category', models.CharField(default='Запчасти и аксессуары', max_length=255, verbose_name='Категория авито')),
                ('type_category', models.CharField(default='Товар приобретен на продажу', max_length=255, verbose_name='Тип запчастей')),
                ('condition', models.CharField(default='Б/у', max_length=255, verbose_name='Состояние з/ч')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя менеджера')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адресс')),
                ('avalibale', models.CharField(default='В наличии', max_length=255, verbose_name='Наличие')),
                ('count', models.IntegerField(blank=True, default=0, null=True, verbose_name='Колличество скачиваний')),
                ('date_last', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
            ],
            options={
                'verbose_name': 'Прайс авито',
                'verbose_name_plural': '4. Прайсы авито',
            },
        ),
    ]
