# Generated by Django 4.1.3 on 2023-03-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minsk', '0006_exportpriceavito'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportpriceavito',
            name='exchange',
            field=models.IntegerField(default=1, verbose_name='Курс валюты'),
        ),
        migrations.AddField(
            model_name='exportpriceavito',
            name='type_id',
            field=models.CharField(default='16-830', max_length=255, verbose_name='подкатегория товара'),
        ),
    ]
