# Generated by Django 4.1.3 on 2022-12-06 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Топливо')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': '3. Топливо',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_mark', models.CharField(max_length=255, verbose_name='Название марки')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': '1. Марки',
            },
        ),
        migrations.CreateModel(
            name='Transmissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип кпп')),
            ],
            options={
                'verbose_name': 'КПП',
                'verbose_name_plural': '5. КПП',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_model', models.CharField(max_length=255, verbose_name='Название модели')),
                ('name_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.mark', verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': '2. Модели',
            },
        ),
        migrations.CreateModel(
            name='Engines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Маркировка двигателя')),
                ('volume_engine', models.CharField(max_length=50, verbose_name='Обьем двигателя')),
                ('type_engine', models.CharField(max_length=20, verbose_name='Тип двигателя')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.fuelengine', verbose_name='Топливо')),
                ('mark_auto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.mark', verbose_name='Марка авто')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': '4. Двигателя',
            },
        ),
    ]
