# Generated by Django 4.1.3 on 2022-12-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='name_mark',
            new_name='mark_auto',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='name_model',
            new_name='model_auto',
        ),
    ]
