# Generated by Django 4.1.3 on 2022-12-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_name_mark_model_mark_auto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engines',
            old_name='mark_auto',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='mark_auto',
            new_name='mark',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='model_auto',
            new_name='model',
        ),
    ]
