# Generated by Django 4.1.3 on 2022-12-11 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0001_initial'),
        ('emirate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedengines',
            name='who_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='enginesinstock',
            name='engine_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.engines', verbose_name='Маркировка двигателя'),
        ),
        migrations.AddField(
            model_name='enginesinstock',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.mark', verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='enginesinstock',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.model', verbose_name='Модель авто'),
        ),
        migrations.AddField(
            model_name='enginesinstock',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.transmissions', verbose_name='Тип КПП'),
        ),
    ]
