# Generated by Django 4.1.3 on 2022-12-06 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emirate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedengines',
            name='order',
            field=models.BooleanField(default=False, verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='purchasedengines',
            name='payment',
            field=models.CharField(blank=True, default='0', help_text='Указать стоимость оплаты или предоплаты', max_length=20, null=True, verbose_name='Оплата/Предоплата'),
        ),
        migrations.AddField(
            model_name='purchasedengines',
            name='who_order',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
    ]
