# Generated by Django 4.1.3 on 2022-12-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedengines',
            name='fuel',
        ),
    ]
