# Generated by Django 4.1.3 on 2022-12-08 15:11

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('emirate', '0003_alter_purchasedengines_who_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedengines',
            name='engine_mark',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field=('mark', 'fuel'), chained_model_field=('mark', 'fuel'), on_delete=django.db.models.deletion.CASCADE, to='cars.engines', verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='purchasedengines',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mark', chained_model_field='mark', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель авто'),
        ),
    ]
