# Generated by Django 4.1.3 on 2022-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emirate', '0005_alter_purchasedengines_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedengines',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость закупки'),
        ),
    ]
