# Generated by Django 4.1.3 on 2022-12-08 15:22

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('emirate', '0005_alter_purchasedengines_engine_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedengines',
            name='engine_mark',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mark_auto', chained_model_field='mark_auto', on_delete=django.db.models.deletion.CASCADE, to='cars.engines', verbose_name='Маркировка двигателя'),
        ),
    ]
