# Generated by Django 4.1.3 on 2022-12-08 15:36

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_name_mark_model_mark_auto_and_more'),
        ('emirate', '0006_alter_purchasedengines_engine_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedengines',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mark_auto', chained_model_field='mark_auto', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель авто'),
        ),
    ]
