# Generated by Django 4.1.3 on 2022-12-08 15:43

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_mark_auto_engines_mark_and_more'),
        ('emirate', '0007_alter_purchasedengines_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedengines',
            name='engine_mark',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mark', chained_model_field='mark', on_delete=django.db.models.deletion.CASCADE, to='cars.engines', verbose_name='Маркировка двигателя'),
        ),
        migrations.AlterField(
            model_name='purchasedengines',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='mark', chained_model_field='mark', on_delete=django.db.models.deletion.CASCADE, to='cars.model', verbose_name='Модель авто'),
        ),
    ]
