# Generated by Django 4.1.3 on 2022-12-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderemirate',
            name='date_add',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
    ]
